---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-name
  namespace: default
spec:
  encryptedData:
    foo: AgA+tgJVhBeQDLTWtJceTGJa6bkQvKUwifr4NT/xbobsqrvD/rZKtt4l1AmTX/qMrQMLpZyxiSl63vTK7Ec6vetndPElFQgacXLKqayX/v+Z722EmSmz5e7aoaQK/8m2cW91ydMx23Sa5LOiCHKL632auGJrIKAIjCKLcCbS7FEx080lYX2VWVj7qGFZKWt95Iha8YlrCGY/C4iSiheIiBomutoPb0gg6KcTNfv/HTXAGEpiYV/R83Gwh9MsHIINa5pdHhj9fBarX1aeQ2hUgrwIyQ/TAnDuobQntGmTqNU3F28vvKGjzyqHMok8JjYoVl+WIBtmracbqYRahBqFriJpBPl0YWZBwCtv1wTX3QXNvmssud9RFNDJiS3fG4m7lemaMbLyU4tOuHx/6er9xgR8dPH1wvbkswxsiPVgXb11DSb8EjAJzyRtBIjA0P1kOuy+LgH7YXOIzkf1lo079e15RB8GJFl/4Oh4NfLFWipm60o1DBoaG4tPU3wc3TiqUQn4Sc630dfeTZDITSFroHJSzuICfNJ8zZJuYn1WKjrqx54hOp4miHeT9sc5XdjL6fB5+FlZoOQ0TZTNmTq/bpq+w+jRgJaY9AMjeUyRnnWfyvGDu7ZBCmjUZSyZj3O2KAVV2DJ3uTG7Q+dHqZxf7DMsU/D1jch0mcH1Hcwu34ctYvPe4h9JhFFfbxcPcvQUK8ABzYs=
  template:
    metadata:
      creationTimestamp: null
      name: secret-name
      namespace: default
