name: bio-check

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - appnet

  api:
    build:
      context: ./bio_check/api
      dockerfile: ./bio_check/api/Dockerfile-api
    container_name: api
    environment:
      - MONGO_URI=mongodb://mongo:27017/service_requests?retryWrites=true&w=majority&appName=bio-check
    ports:
      - "3001:3001"
    networks:
      - appnet

  worker:
    build:
      context: ./bio_check/worker
      dockerfile: ./bio_check/worker/Dockerfile-worker
    container_name: worker
    environment:
      - MONGO_URI=mongodb://mongo:27017/service_requests?retryWrites=true&w=majority&appName=bio-check
    networks:
      - appnet

volumes:
  mongo-data:

# secrets:
#   my_secret:
#     file: ~/.env

networks:
  appnet:
    driver: bridge


# 1a. build base image
# 1b. push base image to ghcr
# 2. docker compose up
# 3. docker compose down
# 4. inspect worker and api containers to test
# 5. push worker and api containers to ghcr
