services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - appnetwork

  gateway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./gateway/Dockerfile-gateway
      # dockerfile: Dockerfile
    image: ghcr.io/biosimulators/bio-compose-server-gateway:0.0.1
    container_name: gateway
    ports:
      - "3001:3001"
    networks:
      - appnetwork
    # command: conda run -n server uvicorn gateway.main:app --host 0.0.0.0 --port 3001 --reload
    depends_on:
      - mongodb

  compose-worker:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./worker/Dockerfile-worker
      # dockerfile: Dockerfile
    image: ghcr.io/biosimulators/bio-compose-server-worker:0.0.1
    container_name: worker
    networks:
      - appnetwork
    # command: conda run -n server python worker/main.py
    depends_on:
      - mongodb

networks:
  appnetwork:
    driver: bridge