# Worker microservice

FROM ghcr.io/biosimulators/bio-check-base:latest

# os deps
RUN apt-get update && apt-get install -y libatlas-base-dev \
    libhdf5-serial-dev \
    swig \
    libboost-all-dev \
    git \
    meson \
    build-essential \
    gfortran \
    libopenmpi-dev \
    libspdlog-dev \
    libpugixml-dev \
    cmake \
    gcc \
    g++ \
    petsc-dev \
    software-properties-common \
    && add-apt-repository ppa:fenics-packages/fenics -y \
    && apt update \
    && apt install -y fenicsx \
    && rm -rf /var/lib/apt/lists/*

# copy content
COPY . /app/worker

# install pysces
RUN poetry add \
    meson-python \
    meson ninja \
    && poetry add pysces --extras=sbml \
    && poetry add biosimulators-utils --extras=logging

# install biosimulators deps
RUN /app/assets/install_deps.sh /app/worker/requirements.worker.txt

WORKDIR /app/worker

RUN python3 -c "import os;files=os.listdir();import shutil;[shutil.rmtree(f) if '__pycache__' in f else None for f in files]"

ENTRYPOINT ["poetry", "run", "python3", "main.py"]
