# Worker microservice

FROM ghcr.io/biosimulators/bio-check-base:latest

# hdf5/amici deps
RUN apt-get update \
    && apt-get install -y libatlas-base-dev libhdf5-serial-dev swig libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

# copy content
COPY . /app/worker

# install deps
RUN /app/assets/install_deps.sh /app/worker/requirements.worker.txt

RUN mv /app/biosimulator_processes /app/api/biosimulator_processes

WORKDIR /app/worker

RUN python3 -c "import os;files=os.listdir();import shutil;[shutil.rmtree(f) if '__pycache__' in f else None for f in files]"

ENTRYPOINT ["poetry", "run", "python3", "main.py"]

# img_version=1.0.1
# ./assets/scripts/build_image.sh compose_api "$img_version" && ./assets/scripts/push_image.sh compose_api "$img_version" AlexPatrie && ./assets/scripts/build_image.sh compose_worker "$img_version" && ./assets/scripts/push_image.sh compose_worker "$img_version" AlexPatrie