openapi: 3.1.0
info:
  title: verification-service
  version: 0.0.1
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /utc-comparison:
    post:
      summary: Compare UTC outputs from Biosimulators for a model from a given archive.
      operationId: utc-comparison
      parameters:
      - name: simulators
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          description: List of simulators to compare
          default:
          - amici
          - copasi
          - tellurium
          title: Simulators
        description: List of simulators to compare
      - name: include_output
        in: query
        required: false
        schema:
          type: boolean
          description: Whether to include the output data on which the comparison
            is based.
          default: true
          title: Include Output
        description: Whether to include the output data on which the comparison is
          based.
      - name: comparison_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Comparison ID to use.
          title: Comparison Id
        description: Comparison ID to use.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_utc-comparison'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingJob'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /fetch-results/{comparison_run_id}:
    get:
      summary: Get the results of an existing uniform time course comparison.
      operationId: fetch-results
      parameters:
      - name: comparison_run_id
        in: path
        required: true
        schema:
          type: string
          title: Comparison Run Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchResultsResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_utc-comparison:
      properties:
        uploaded_file:
          type: string
          format: binary
          title: Uploaded File
          description: OMEX/COMBINE Archive File.
        ground_truth_report:
          type: string
          format: binary
          title: Ground Truth Report
          description: reports.h5 file defining the so-called ground-truth to be included
            in the comparison.
      type: object
      required:
      - uploaded_file
      title: Body_utc-comparison
    FetchResultsResponse:
      properties:
        content:
          title: Content
      type: object
      required:
      - content
      title: FetchResultsResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    PendingJob:
      properties:
        job_id:
          type: string
          title: Job Id
        status:
          type: string
          title: Status
          default: PENDING
        omex_path:
          type: string
          title: Omex Path
        simulators:
          items:
            type: string
          type: array
          title: Simulators
        comparison_id:
          type: string
          title: Comparison Id
        timestamp:
          type: string
          title: Timestamp
        reports_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Reports Path
      type: object
      required:
      - job_id
      - omex_path
      - simulators
      - comparison_id
      - timestamp
      title: PendingJob
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
