openapi: 3.1.0
info:
  title: verification-service
  version: 0.0.1
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /utc-comparison:
    post:
      summary: Compare UTC outputs from Biosimulators for a model from a given archive.
      operationId: utc-comparison
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_utc-comparison'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /fetch-results/{comparison_run_id}:
    get:
      summary: Get the results of an existing uniform time course comparison.
      operationId: fetch-results
      parameters:
      - name: comparison_run_id
        in: path
        required: true
        schema:
          type: string
          title: Comparison Run Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchResultsResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_utc-comparison:
      properties:
        uploaded_file:
          type: string
          format: binary
          title: Uploaded File
          description: OMEX/COMBINE Archive File.
        comparison_params:
          allOf:
          - $ref: '#/components/schemas/UtcComparisonRequest'
          description: Simulators to compare, whether to include output data, and
            descriptive id of comparison.
        ground_truth_report:
          type: string
          format: binary
          title: Ground Truth Report
          description: reports.h5 file defining the so-called ground-truth to be included
            in the comparison.
      type: object
      required:
      - uploaded_file
      - comparison_params
      title: Body_utc-comparison
    FetchResultsResponse:
      properties:
        content:
          title: Content
      type: object
      required:
      - content
      title: FetchResultsResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Job:
      properties:
        id:
          type: string
          title: Id
        status:
          type: string
          title: Status
        results:
          anyOf:
          - type: object
          - type: 'null'
          title: Results
      type: object
      required:
      - id
      - status
      title: Job
    UtcComparisonRequest:
      properties:
        simulators:
          items:
            type: string
          type: array
          title: Simulators
        include_output:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Include Output
          default: true
        comparison_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Comparison Id
      type: object
      required:
      - simulators
      title: UtcComparisonRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
