# create kustimization.yaml file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biochecknet

# CURRENT STABLE VERSIONS OF CONTAINERS: api: 1.11.8, worker: 1.11.6

images:
- name: ghcr.io/biosimulators/bio-check-compose_api
  newTag: 1.11.9
- name: ghcr.io/biosimulators/bio-check-compose_worker
  newTag: 1.11.7
- name: mongo
  newTag: 8.0-rc

replicas:
- count: 1
  name: biochecknet-api
- count: 1
  name: worker
- count: 1
  name: mongodb

resources:
- biochecknet-api-secrets.yaml
- mongodb-pvc.yaml
- secret-ghcr.yaml
- biochecknet-ingress.yaml
- ../../config/biochecknet
- ../../base

