# create kustimization.yaml file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biochecknet

# CURRENT STABLE PRODUCTION VERSIONS OF CONTAINERS(pre-namespace change, pre-deps change):
# api:
# ghcr.io/biosimulators/bio-check-compose_api:1.11.9
# worker:
# - name: ghcr.io/biosimulators/bio-check-compose_worker:1.11.7

images:
- name: mongo
  newTag: 8.0-rc
- name: ghcr.io/biosimulators/bio-compose-server-api
  newTag: 0.0.1-test
- name: ghcr.io/biosimulators/bio-compose-server-worker
  newTag: 0.0.1-test
# - name: ghcr.io/biosimulators/bio-check-compose_api
#   newTag: 1.11.9
# - name: ghcr.io/biosimulators/bio-check-compose_worker
#   newTag: 1.11.7

replicas:
- count: 1
  name: biochecknet-api
- count: 1
  name: worker
- count: 1
  name: mongodb

resources:
- biochecknet-api-secrets.yaml
- mongodb-pvc.yaml
- secret-ghcr.yaml
- biochecknet-ingress.yaml
- ../../config/biochecknet
- ../../base

