# create kustimization.yaml file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biochecknet

images:
- name: ghcr.io/biosimulators/bio-check-api
  newTag: 1.0.2
- name: ghcr.io/biosimulators/bio-check-worker
  newTag: 1.0.1
- name: mongo
  newTag: 8.0-rc

replicas:
- count: 1
  name: biochecknet-api
- count: 1
  name: worker
- count: 1
  name: mongodb

resources:
- biochecknet-api-secrets.yaml
- mongodb-pvc.yaml
- secret-ghcr.yaml
- biochecknet-ingress.yaml
- ../../config/biochecknet
- ../../base

