# Api gateway microservice (CURRENTLY STABLE BASE IS LATEST 0.1.5

# FROM ghcr.io/biosimulators/bio-check-base:latest
# FROM ghcr.io/biosimulators/bio-compose-server-base:latest

# TODO: change this back to latest once stable
FROM ghcr.io/biosimulators/bio-compose-server-base:0.0.5

SHELL ["/usr/bin/env", "bash", "-c"]

COPY .. .

EXPOSE 3001

RUN source ~/.bashrc \
    && conda env update -n server -f config/environment.api.yml \
    && conda run pip install -e . --root-user-action=ignore \
    && conda env export --no-builds > config/environment.api.lock.yml \
    && rm -f spec/openapi_3_1_0_generated.yaml \
    && conda run python3 openapi_spec.py \
    && conda clean --all --json -y \
    && rm -f config/environment.api.yml

# RUN source ~/.bashrc \
#     && poetry install --without=composition,dev,worker --no-cache

ENTRYPOINT ["bash", "-c", "source ~/.bashrc && conda run uvicorn main:app --host 0.0.0.0 --port 3001 --reload"]

