name: bio-check
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - h5py=3.11.0
  # - pip:
  #   - fastapi==0.111.0
  #   - pyyaml==6.0.1
  #   - httpx==0.27.0
  #   - pymongo==4.7.3
  #   - python-multipart==0.0.9
  #   - aiofiles==24.1.0
  #   - pydantic-settings==2.3.4
  #   - tensorstore==0.1.63
  #   - aiobotocore==2.13.1
  #   - biosimulators-copasi==0.1.35
  #   - biosimulators-amici==0.1.24
  #   # - biosimulators-tellurium==0.1.42
  #   - biosimulators-utils
  #   - biosimulator-processes==0.0.36