# Worker microservice

FROM ghcr.io/biosimulators/bio-check-base:latest

# WORKDIR /app

COPY . /app/worker

RUN pip uninstall biosimulators-utils -y \
    && pip install -r /app/worker/requirements.worker.txt \
    && python3 -m pip install --upgrade matplotlib

WORKDIR /app/worker

RUN python3 -c "import os;files=os.listdir();import shutil;[shutil.rmtree(f) if '__pycache__' in f else None for f in files]"

CMD ["python3", "main.py"]