openapi: 3.1.0
info:
  title: verification-service
  version: 0.1.0
paths:
  /utc-species-comparison:
    post:
      summary: Compare UTC outputs for a given species name
      operationId: utc_species_comparison_utc_species_comparison_post
      parameters:
      - name: species_id
        in: query
        required: true
        schema:
          type: string
          title: Species Id
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_utc_species_comparison_utc_species_comparison_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtcSpeciesComparison'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_utc_species_comparison_utc_species_comparison_post:
      properties:
        file:
          type: string
          format: binary
          title: File
        simulators:
          items:
            type: string
          type: array
          title: Simulators
          default:
          - amici
          - copasi
          - tellurium
      type: object
      required:
      - file
      title: Body_utc_species_comparison_utc_species_comparison_post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    UtcSpeciesComparison:
      properties:
        mse:
          type: object
          title: Mse
        proximity:
          type: object
          title: Proximity
      type: object
      required:
      - mse
      - proximity
      title: UtcSpeciesComparison
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
