openapi: 3.1.0
info:
  title: verification-service
  version: 0.1.0
paths:
  /files/:
    post:
      summary: Create File
      operationId: create_file_files__post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_create_file_files__post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /upload-OMEX-archive:
    post:
      summary: Upload Archive
      operationId: upload_archive_upload_OMEX_archive_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_archive_upload_OMEX_archive_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /exec-files:
    post:
      summary: Create File
      operationId: create_file_exec_files_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_create_file_exec_files_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /utc-species-comparison:
    post:
      summary: Compare UTC outputs for a given species name
      operationId: utc_species_comparison_utc_species_comparison_post
      parameters:
      - name: species_id
        in: query
        required: true
        schema:
          type: string
          title: Species Id
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_utc_species_comparison_utc_species_comparison_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtcSpeciesComparison'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_create_file_exec_files_post:
      properties:
        uploaded_file:
          type: string
          format: binary
          title: Uploaded File
      type: object
      required:
      - uploaded_file
      title: Body_create_file_exec_files_post
    Body_create_file_files__post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      required:
      - file
      title: Body_create_file_files__post
    Body_upload_archive_upload_OMEX_archive_post:
      properties:
        uploaded_file:
          type: string
          format: binary
          title: Uploaded File
      type: object
      required:
      - uploaded_file
      title: Body_upload_archive_upload_OMEX_archive_post
    Body_utc_species_comparison_utc_species_comparison_post:
      properties:
        uploaded_file:
          type: string
          format: binary
          title: Uploaded File
        simulators:
          items:
            type: string
          type: array
          title: Simulators
          default:
          - amici
          - copasi
          - tellurium
      type: object
      required:
      - uploaded_file
      title: Body_utc_species_comparison_utc_species_comparison_post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    UtcSpeciesComparison:
      properties:
        mse:
          type: object
          title: Mse
        proximity:
          type: object
          title: Proximity
        output_data:
          type: object
          title: Output Data
      type: object
      required:
      - mse
      - proximity
      - output_data
      title: UtcSpeciesComparison
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
