FROM ghcr.io/biosimulators/bio-check-base:0.0.1

WORKDIR /app

COPY . /app/bio_check/worker

RUN poetry add \
    biosimulators-copasi \
    biosimulators-amici \
    biosimulators-tellurium \
    biosimulator-processes \
    && poetry add biosimulators-utils --extras=logging
    # h5py \
    # numpy \

# TODO: For CMD, run a main python file that is a while loop checking for jobs
CMD ["/usr/bin/env", "bash"]
