FROM ghcr.io/biosimulators/bio-check-base:latest

COPY bio_check/worker /app/bio_check/worker

RUN poetry add \
    biosimulators-copasi \
    biosimulators-amici \
    biosimulators-tellurium \
    biosimulators-utils --extras=logging \
    biosimulator-processes
    # h5py \
    # numpy \

# TODO: For CMD, run a main python file that is a while loop checking for jobs
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
