openapi: 3.1.0
info:
  title: bio-check
  version: 0.0.1
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /utc-comparison:
    post:
      summary: Compare UTC outputs from for a deterministic SBML model within a given
        archive.
      operationId: utc-comparison
      parameters:
      - name: simulators
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          description: List of simulators to compare
          default:
          - amici
          - copasi
          - tellurium
          title: Simulators
        description: List of simulators to compare
      - name: include_outputs
        in: query
        required: false
        schema:
          type: boolean
          description: Whether to include the output data on which the comparison
            is based.
          default: true
          title: Include Outputs
        description: Whether to include the output data on which the comparison is
          based.
      - name: comparison_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Descriptive prefix to be added to this submission's job ID.
          title: Comparison Id
        description: Descriptive prefix to be added to this submission's job ID.
      - name: duration
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          description: Duration of the simulation, only if passing an sbml file as
            uploaded_file
          title: Duration
        description: Duration of the simulation, only if passing an sbml file as uploaded_file
      - name: n_steps
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          description: Number of simulation steps to run, only if passing an sbml
            file as uploaded_file
          title: N Steps
        description: Number of simulation steps to run, only if passing an sbml file
          as uploaded_file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_utc-comparison'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtcComparisonSubmission'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /fetch-results/{job_id}:
    get:
      summary: Get the results of an existing uniform time course comparison.
      operationId: fetch-results
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtcComparisonResult'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_utc-comparison:
      properties:
        uploaded_file:
          type: string
          format: binary
          title: Uploaded File
          description: 'One of: either an OMEX/COMBINE Archive File or SBML File.'
        ground_truth_report:
          type: string
          format: binary
          title: Ground Truth Report
          description: reports.h5 file defining the 'ground-truth' to be included
            in the comparison.
      type: object
      required:
      - uploaded_file
      title: Body_utc-comparison
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    UtcComparisonResult:
      properties:
        content:
          title: Content
      type: object
      required:
      - content
      title: UtcComparisonResult
    UtcComparisonSubmission:
      properties:
        job_id:
          type: string
          title: Job Id
        status:
          type: string
          title: Status
        timestamp:
          type: string
          title: Timestamp
        comparison_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Comparison Id
        omex_path:
          type: string
          title: Omex Path
        simulators:
          items:
            type: string
          type: array
          title: Simulators
        ground_truth_report_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Ground Truth Report Path
        include_output:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Include Output
          default: true
      type: object
      required:
      - job_id
      - status
      - timestamp
      - omex_path
      - simulators
      title: UtcComparisonSubmission
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
