# Worker microservice

FROM ghcr.io/biosimulators/bio-check-base:latest

# WORKDIR /app

COPY . /app/worker

RUN pip uninstall biosimulators-utils -y \
    && pip install -r /app/worker/requirements.worker.txt \
    && python3 -m pip install --upgrade matplotlib \
    && python3 -m pip install --upgrade amici

WORKDIR /app/worker

CMD ["python3", "main.py"]