 # Api container

# TODO: Ensure read from BASE_VERSION.txt
FROM ghcr.io/biosimulators/bio-check-base:latest

WORKDIR /app

COPY . /app/bio_check/api

EXPOSE 3001

RUN ./assets/scripts/add_deps.sh "tensorstore aiofiles aiobotocore pyyaml httpx uvicorn"

CMD ["uvicorn", "bio_check.api.main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]
# "poetry", "run",
