 # Api container

# TODO: Ensure read from BASE_VERSION.txt
FROM ghcr.io/biosimulators/bio-check-base:latest

WORKDIR /app

COPY . /app/bio_check/api

RUN poetry add tensorstore aiofiles aiobotocore pyyaml httpx uvicorn

# TODO: add this and make it work
# COPY ./assets/scripts/add_deps.sh ./add_deps.sh

EXPOSE 3001

CMD ["uvicorn", "bio_check.api.main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]
# "poetry", "run",
