apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 0
  template:
    metadata:
      labels:
        app: worker
    spec:
      # securityContext:
      #   runAsUser: 10001
      #   runAsGroup: 10000
      #   fsGroup: 10000
      containers:
        - name: worker
          image: ghcr.io/biosimulators/bio-check-worker  # push to ghcr.io/biosimulators
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "2000Mi"
#              cpu: "500m"
          envFrom:
            - configMapRef:
                name: worker-config
            # - configMapRef:
                # name: shared-config
#          command: [ "/bin/sh", "-c", "env; cat /run/secrets/worker-secrets/dbpswd" ]
          env:
            - name: MONGO_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongo-password
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongo-username
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: google-application-credentials
          #   - name: jmspswdfile
          #     value: "/run/secrets/worker-secrets/jmspswd"
          #   - name: dbpswdfile
          #     value: "/run/secrets/worker-secrets/dbpswd"
          #   - name: vcellworker_privatekeyfile
          #     value: "/run/secrets/jwt-secret/workerprivkey"
          #   - name: vcellworker_publickeyfile
          #     value: "/run/secrets/jwt-secret/workerpubkey"
          ports:
            - containerPort: 3001
          # volumeMounts:
            # - name: worker-secrets
            #   mountPath: /run/secrets/worker-secrets

            # - name: nfs-primary-pvc  TODO: revisit this.
            #   mountPath: /n5DataDir
            #   subPath: n5
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: worker-secrets
          secret:
            items:
              - key: mongo-password
                path: mongo-password
              - key: mongo-username
                path: mongo-username
            secretName: worker-secrets
        # - name: worker-secrets
        #   secret:
        #     items:
        #       - key: dbpswd
        #         path: dbpswd
        #       - key: jmspswd
        #         path: jmspswd
        #     secretName: worker-secrets
        # - name: jwt-secret
        #   secret:
        #     items:
        #       - key: workerprivkey
        #         path: workerprivkey
        #       - key: workerpubkey
        #         path: workerpubkey
        #     secretName: jwt-secret
        # - name: nfs-primary-pvc
        #   persistentVolumeClaim:
        #     claimName: nfs-primary-pvc
        # - name: nfs-archive-pvc
        #   persistentVolumeClaim:
        #     claimName: nfs-archive-pvc
#        - name: nfs-secondary-pvc
#          persistentVolumeClaim:
#            claimName: nfs-secondary-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker
  name: worker
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    app: worker