---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: dev
spec:
  encryptedData:
    mongo-password: AgBixA/ICcI8fYm/ehKlexlEkEkj4998nWas/Q5g90M6z9zd/Az2o71sudZ7rzyg8ZSI4s9Qm2G4GGEMjvj3YM83TmSxrgeYUVrFsGNN7la0IWaACxDwTwX8tE6H1lAUV6k1x8jYxMxYyiEnE4sOk4TR/+QsK1q/Uelwa4VdIu+ls+mhDzCN8oqtN5XEzBwhdDn+ooaRqiDGDxXMiI0zRhOat6Hk//Pc7qpPkLpL9O7r2HS+Ks2hQD7c+UFW3+LZKfmiByhemdzLz/55aEPORfN1Fp2YwZebb4XseuvcYhz7uRHd+nYh7bqssK+GaHmIpjhOPhJ+TSwvdsW2mAGnLUCt3NP8wGM8+XBBkxY1/LhqwopKOkvDSPj8IWOBXOu7y/ePeTvV8cdy3ny7OZAs9BgSO7tplzPJgqH1qWYPyrtuyD0O9gPPUZI47Hk/WtOdXLtCtE7FljGvmqodkUK1YGTyjZmZMAHLSMUxyBB7Wp97iO3s4BEDVWVibng/IPLQvF7gBEt6B4Cm6LtxHEqt4QauTQXwtRMnlYpvDmwRkQzbDvMqRBZqL8piRjJsfOM0BBfsteZuXMvnIh7RjpK8IQ/Sw943ozKBOINSg244J5esEO8TlTLTG5PV2eUQVimhYvpeXodHBMUXxKcDAhwwVRGkhCHWiy1ADLbRzoDj+Lnh6HMIFhew3PT4QBm1TJ2L6nBIPA509w==
    mongo-username: AgCWPIRo8hfRtUsywFWXnjv4XvvFsTVWRAlbcftUNbrTNw3rGSDZL5iebevZ/j4QNqDVgTmswPazcoP6mCkQqmOm3B0GMKMvYZ/wEZ50bsouikQrORqzKBPogv4Y0fVm+XbEf3V8Annr+7M/sV7lYEOEjyTVhnp6riV33MuVIIOziYUp+VdLc77DT/k4MNVVWop53J8yJo6WvL5QFBOyw+gV7S3GCpIx9kGjboyuBj9W/cII8Fn0zu1FfQ1D8oYPXIy25K58NUTyPFsBScYz52VTMZkrpVYLvCPp6GRSAZzZQcebVCjfXOAmOpm9+QMbau+DrcNV+PuwZ/z9R4hiQmfsE7BHsXEBX+mSbb5xyjS06DCUkb/uyQv3YQduM7MoFUw4hMq0vAtX1WtdsutQv0Igq3sVwLjqZ3ZwBWalXOj0/VAm1X3bcomqd64KRa4m/NbS2Rl/RKKbUtsx8+Yq7sxh0IaxruQv61k40NYiSXzoB3/xuXlPLtrzgxzrhsro/w9kC1GqqeDOnTbqwEa8sNRt3IBZlGB5aTlm7W7ruz8ZccGwS9hCSYBsL+xdJNbo6a7E2/N/hPjcrIcbS+64OEyOPQzHUf0UkCU34JZbYe7nWlWsiiXa9AWSt6gnSZdThzZS6UEdjFZkfCDaWWji9hWVPjIqYsxUmrDaK5vY5lwUQTbub5voFTEFX+G8+1qaPd5GzgjHew==
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: dev
