---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: dev
spec:
  encryptedData:
    mongo-password: AgCE298zEVF4oEvyS8tsv67z7uajRdD2p08iszseDdtY/PjBeKwme6V97tW546WOqyPFaM/7NeSjSrA2YE6gfgfQ3uyyqgpigGMS/hwlwxjVbJ79i7Ri3pBjwF33k1lQzk+FHqeHORUkl+5KZSHsx0s3cm532Rk6UGAFEOSTLctK8zxiK43LfIcsJP9WmG5h4sDkRMMEmgxl+wfHakn/ARRbWCDJIBKXwaEk4J8bkQPgL9XneM3WUoSSy5ihwrK5t3OJJ+IxKT2W/FmS/gCA92wUTwE24P8IoxzF/+SFSf8XOMZTmQo5N9/T5tU0q+J9KnyZYmvdFu/3Frly5g1JdWYmMNFnMaZt1IoMn9BOnHT/ZbUjFuMTQBkrSAIe5vJdQQ0lwv0l/Ok56M3uhnNxh9V7WHNzCZfoN805Chk/jzIJe+soCstH13QY+ZzS6Eqd6t4xgFGoF4JzE67aIk3I5DZdeEoc7gwjhbzB08clzfd3Ipuw0HGun34l3oPUGQ5hQW2RjnJswQwiU0iCJNdwEWjnpEqScUi+MMmKrLGclWpp+1x6Y5+tYqCHeJuW2ymTLttgvsbU/Z0YxrI0uu9rYPsyHc0UiiP57PsewTWGEY067p9p6MPAdBKP7F16+rHUPXmo+1yo0zDzh33ki4ciowNvCM61Lpsklekl38Wd0ru0RLmY03mrybgmGbDYqUAPfu8eKd3MQw==
    mongo-username: AgAH63WZ1oBTzhgDc4Pj187wjwyrTcQGgzUxQzxdyMcKMaQJm/AUSzVw8EEUNoa04jWaHRoL5gbmXVcKjbKm6wbI/ol17Kgi01YUhX6u1CMHPhhEEbq9ikpn4i1wPHvIGdErm8VZyU3ejMQMmu1mvzOxICsxutFrRu/eFdPWLPomyqheRCNeMnunVwmGOsbIG1Eu7QBnJNuYWtX2Sc1hs4Ob7aKKOb6HZiMrLyVlfcugWgTWXw/IQmv522v77QuDF6vPrqIV51chN9LOIs8AhKYkKM/FcEmypmYa7nhfHT7D9GNmEw86ujlq2rwZAAUdiaNSYBeN+YnFol2wVdfd3I9+f1Vit/QKoRtID3M0aJS6PbksD1AVxnAQCItPGsQffpepr3K9wBOZn6n98N8P9PT+8BEWTLfiTbJIARH/qLshjMzNIuCCLWSh2B69lGuiNxYXOHMsez9x8VXGmg1Zy0lJ/LfA518YHF7bpETw5K5pKYmbwWVNyyxxRURKJOeJGuBmy3/2kUeaxc/Cn4vejUSJpRQJPIIoMEHrcSg5Af3yNy4cOpCvODdmmyHy7B34DQm8+YfxKsRPwp4McVhDyaRg9Ic3f598n7w00sYA6Pzm6rg9QNWjvyXI+AgqgP0VreXuEc1WR4u80q/k7I3UhnoYz3rVPTDHOA3koHzrxSIroP1g/rjCeayXu36ISh01KONkgrHpUQ==
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: dev
