---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: dev
spec:
  encryptedData:
    mongo-password: AgCL8OpwkoKTuRwbGukSPfMLYpSmOKCgumHyCZiZfbUJI/Wg2YYl6HAloS1bgY0QPUqImYLAZDDUXSO98hfGnWaPGzq/DFZIqx5NL5lCzzzrxnfLZhv3qFUInC+1H8GB44oNRY8nlNkr7tA6Z34bKV9iMt1luK6XlLKGl+1eH/DcMI3Bhn3zKMQe5sZzX0+urcJF9jO6STVdeJaBvRNw2u12NeOy16IJRn/b0mWbPOS/ry58vgg+qoith3IFX5slSvTgP7JuNuYc9aixiMz6LOpbE+neEpKfP9OS4OSGIFDCnuHJu2DxI65gDm1zn4HvaTXoXqaH3iPy46wPxuz7X+2Qe3yslXRUugd2v8/yL8crui9C/yxNTpD5gWUSGY5FjUynPfO9AaC+SFw2Qac9hVTV6EGTP5G4q0baiBiaz5qbF+l7JgT4bmlkJRhv7D2rhSrKENshitQrsWDTYf1ZO2Fnj1huifTwKzbNlF8YHxtRCoaIA6Il3hV5QwEKJ8E3KN1OsDxH8QrbGv263QJKjobVltF7UKmjVhKyoCScWRFu9W9lNUG01DOK2Orc1bz9zo+iUsX/PDROyoM5zrmVJtrWBC9TPjp7otooQQTvzPb4+KGoNJS+yxz55w+USpPXym9DE/L01ZaufWsluw+MYX7iq+8PJq9mALgbvHuBOZCRQGTlSl3xdDmjxZq1QdjTWgs0K+oGJg==
    mongo-username: AgAjoIhs+7j3uLnYV89Xa+CAmEfVyV0aOiQ9kYG31O0tTFlX3QFAS47+qAWBRnkrubec8skHuGVhoejMZrSs3mwPd6XDgF/SBW0/faOG+0HTM2NinNGEaiF1urhHVpSHAovlQNGTPnjknD9o++MPO/TLRoWam7s5RqDrbPag95LubGsnlkFpL7/CMdlWUzeNjcMD53dyj/q2wcqda+aORGI0K8g0phnjth0QYB/f5hlbdSebykeo7nkufSG+Fje/xN4StUCfnAn+PAgBTy4yn3Evhoig6U+YlCzu81rcf5VjAuUN9JexCP2vhIH6LSB85Rc8pDXijUSE527xz7xH2p5K9x6SGPqhfjhYhjXHtSMT20rYXw+FyM+V9jL5kTM9gu2/1vj3bUD9HHx6cv/iFiD/n6C1UEerqGnxg/EUTbZshyNg3Kx/nyYOiehFTmPP6TNCPEnUFZ5La4mohhKKBbgcCXXQOIQF4EmpXTcajBnemK5b28J6SuL4cihkgERkWbklxQyYf7VQiNB7GqDyqbbJgj+1N9JCdLZetDJsaCmLzUQ5N+fvLX15Xp619wP52egAzArGiEE/R61jyHfVNNiOattZnFWw0zhV+TyrZbFD+AplNQcHA8fSV9XR7silD0xjE8YCR7A0odBrWkwkTQ1qagdFOetnHOIWuGXOpp/YZiQiOn2pIgJcVW3qdvj4yr9fCUj7ww==
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: dev
