---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: dev
spec:
  encryptedData:
    mongo-password: AgA5uR+W2jkrdT6Ft3Bpt7ngyKVBJdVfGwB37RZTRHtbvoq4/XpwFTUL2UU/oAPzdgI4CgEI+w3YS7uZedCn/5HIDrfjApf5Jzc9uaFVsATijn6Ql7AppiYd5clHotGjLZpk5LHXaSKCtTHwSUi2iAACLjWnhkvgSMOlvMLu0JXaad084qr8VTLCMBEZvV6Dg2d49GX3WLXGpLiwokWSa2Th+lj1hx7/xnC0zmq4d6eF27mxGdmKpQ5j9ArCvL9ipGtbTJmhzyOpNJm5TxsXtijh8oUVv7SGjc5H3KItgg36cx45GPKLFFomQZAc5rLj51bgV0LyAZt8VY/6ZnRd2OFA18Y9FC6YPQgvmcnPST04udn4FcxVeRiorj3LjdqXnmBatBMHe9uqkt1M1IIZfmT5cACO5KJQKm5rfJ6lTw7gx8jRreCBOL4RsXrUORRDWiZQUHzPz1xAu2mVpHbEdDaYr3WoZAyZsDDZxmZpHfWg1FP7e5GKZW/Ryy6+fZlhsHt1IYyi2DTcAj3/HKOmg5WobvuSmxcpQlkTP2E55pLvdje0itrR8pbu6EssyNvhOgdpVWEeuB5qa7ZXaymPvarDeKmNVwtdilrx5hJnVQMVg0ihOn9+CskqaFKDFQWQBA4SdZ4rNGQdCDDUST2NgCaeGSF5GggVr/BCcV2z6aJ9205SezYUpOuRLKP31O1481am83ystQ==
    mongo-username: AgDbUfGZj+0Na1y8YpNcxJ4VHml4ZDFB7n4dH6xwxMsm2eeosBzvwJ4AUykG8LQLVJ+UZbUiIKAZpDpqE5yAM0ON7XTs+P9L7SXDZLZNVq+VcrvmIpl1C6Abc7B8TsIK9ycGX3lXZZLI4VrBD41uo1e5Y2+3ReMxV54YByol0C3tNa2Ugu6WjxqhigZW8pSguil2mD/xAYH3v1R4/q1wND20MwUDeQMfrzM01Geohk7+vtX6ol5/llx/ROtpcBA1AOgDzWbhK5Af5NFxxx4MXH/zJxR9JLcwLxbazValbj7/Qmd1vzUrMw+03wHChpES3tOaMBelMi0bBNV/o1mTojzK7Rf1GlRb/i2G5w63ZnM63RFi2HCz5oNMoHduTT8ges0/mCwTj03U3dDYVcuEpWnQYmQkKEr1RTPRyK9t1ERZNkwY8YvHN3L+lCX/2ralethK68hmrXWuCL6+f1ClH/RlMSWSaF33O+yIPCL9yU8VjBgIkPTT/w7snY9tRwHEIhtQIr1f2kGdU4RXLSkBVKowOoIskScK83arSpgBU1qN1viGiW/4O7oq9w9jr1osPbYCSigT47ZBkd1rWMgm9agwon1yM+fJl9g76liaW9gaYlsm+neXblHkNc7w2nPAbTm5NjDgU8/sGO8O7RQ/Ep91av9hzfbqyvND95RRRv5W8kHB3gbjTzU3z/5YJXh1STeLlRPpeQ==
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: dev
