---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secrets
  namespace: dev
spec:
  encryptedData:
    mongo-password: AgCu4lVnpBsqzkLtgxhkIgoEthrKoRpuGs7wBrkqu+OpOrdI/rJCSU4wS9TKOsQ/aHW9qsghd0lvFM0+aM7B8BGfRt9oFZ1fdIEAVDvlPPE49mx3zDsGp9mJetSAsXImgjZdvfKiKUUhVDUlgfgSXHVxurNhv1dnGWoYbX7NsZ0cekzxG8l5C2N2KMISEUHwvVYWRJHQ2BUPR8gSq8frAInQxP9UVoDNp1aQ7RhayQwmYF98wGvHWHv9U3VGQ/ZBClZG9P1x27+pVZMhOgARXhAVO3PPoBN7FZb37WFbhAaqIZoCKWc04zHkXqX3+0UGAUk1V0TPsOGLMwDeFfC81lxZkRGSqFhzDE3rXmvnNwQOl4P14SOlm0KmS6Hot8qI2qnBXYYzkVGedxO2xWkjITsNlGeDvFx9EwttZ6pahRL3n585vByRfRMI2DUIR2Rz6H+PDt0F9nut/j0HS2ITxwhGwSiEPLV6EpvwmrgEYnzASdXxxq9G68VHFf8U+F1BXE/wOY6dWMinDR3tHcLIPcemO6eQ1g+UsF6D7GiRsWbFqaourFuXnl+FNC5JaouxUUQNH9PXq58LE0IY/q7rKJSdFpP0FdoGkzi1I89EKzzyrknzabhKVpneFh/YrjVhaOLh4boZU37XyW10A+/FPzGQJTGlWyZgOixIPTn0bBLih1VNoLM0T562twXCll7zThmT7m7PXQ==
    mongo-username: AgAdMnZi2VxdfJT/58QNw+xPu/q7A8Tf3jmLZHFsSqFbSTSRGC0z8EGmmZ1hemXlEDF122+GhLfjJ6Jbg6T/ln9QtiKLStuoG4TaUPg//QkcQg239rlG1r1X6aot2W0wsdqiVeBd+Lip/9zdtsgh4p2Z/wiihD/R5yWxpGdCW7CKwuGeH+nwzqgpvMO61B8AQ9uVeu8vJHE1KWywrzIuOZvbcn43nKvvSSREDmHP0QwWLSWWgAhA11SwwcXcM3qLeSD/rjNV1cjBoHWYaxfkB7OJKG08DYwP3UYj95pGJY3wYrtq1/Q16bbP26yvBIlAx42NovIUDybLNBqj6bDn2aIbkEE2SJWkzCLicqPBCxq2Fjr0+eKVKQqtFUwf9HB5RRH2dyJ5Kp4KZlU9QyYsol4bDtQmm4JxcszM4m8zsJcTY+VMx5FWs/HqKb/0188CdRhIQwKzeEWc1TSIkQ+wcWC9ZS3l4lZL85bYVQ99r3whyFtrkz9JO4mruBGuejeJ5FPh7YgKsMLQIaImAQEVi4suX07tSJFnpUalPcV9wriS6E95JpYZdgfSRPAPEsCiNSM/F+N+gL3zyXseoTq2TmySkLPFWFfz3ug+KmKlhUqoDIT96mcVowHrF+muTCHF8MNutUPKt3pXg7aaJKllNIEUxVDexaSf/wxhwxcRy47Sz5kpQ8U2JU5NuvR6nZR6WfVaAuTvOA==
  template:
    metadata:
      creationTimestamp: null
      name: api-secrets
      namespace: dev
