---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAVaKgHJhICJrQSUYVal9+vhZEatf65DFmlkXiXdnE66lrcHEF6Yl4rDPMA6Shh3My8iCXoU77qBMgjirf0sdD8AollajqdM0y2Ql1UKhqxkQp3H4YC2OJ3rpOiw9Cd3fCXbueAYpiY5KC94emSn15u0ivpQEbbZOMM1KJMlv96s2UXC+v8LL1fqXYQtnD+v7U7B6aHOpubgwEh9ASy9YsKAQwrsFzPup0vPUWPYGJD8yjIu4AAnNyv+/O9mC+4ph66Taco5ZxCQxb/EdGUG6DX92ooO5ZnP+s4fQbBZrzhelUwEYIVVMSrzBO/7micfHemT0rKu4EnAkE/vHeoq2GP7DChiUUgYTnrl0G6ZYtnjEtEiMimf4A0N1/RdvH53IwYkdryE2fOBbi/d0/OQYOAJ/DpY0lm4xV0G7db2+g5HIMWLp3TRv8yiPIE2xxn+g2WMC5QaU9LXZfPlpREpoQSQhB31sWee/LlSRM1NPOrhzLHRTjFPLNoLYdxDRbpZKlQY7QLHuUMyM57aZX8XQTemVtiiTfABa4tA65ksFzJEsp1WOTXcueHMqY9MyJFK2yLs5C+CyBwD3emgA4HdPizeZVilU5xxIp11udpLkHcD5Z/WaiDIUsHsrWYCtx6mre4bb6+ApOk4xUTr2rS8tXKXfM/185zK2JUm1et39M34zieLlZmTVTMHSvUoQnkYqaheGrQqX24BwdgkNG+/LaGOXVyc9f72jutEsfpdPigI1abMyu4M/r4Fq8C8lVNIB4vl5qOPq/KyzF7pusIqlzy6C7yKb+PEEG2rcbSFRx9nCPQAj3IJo4lyyksACB9dH269rxLjKq/upPT8U1rTn9qeoMh91qSzAw6sQzXFYlGAkghN6NkcWp67psZihKFFoVSYHKiiRgCm+GLzOiGTJSnkxybHqUVtTsBixXuOGspe2vS8DpMNmN6rUrGb/WFOK72nmcF7wu8dqykBqP1bPPuRTldc0Dwhw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
