---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgArshzV4uP1tsK85XP0j1Lr5YUXGRgBdBMWbWUhR33Yuy6k4ZrBbr3K0+PjRJNAaLMaFi7qAy6f/irVmIMqW+zYvT4Ks2svWK0n2dQbwbfoMZ54JJ0XIf5wSBfj42nSYlH1vQWQK0T32rXOuZRpVKQNH27G7y+WPY+eqjqsiwmU6uk+mpxx7tEQNL8ZKr3jkqVRJf0oHAU+YSKNHf1XcpnZXS959deSc7yiI0nLZs+yhJbpLhG5TP4ZQtCCJxfR6heX0KzcxaVjrUlDviYpIjdLSPdc8W/SimRzenu+Zr+D8u6DsKOVsGVfvC1VPq68xEMVW0Sk9oAlHNxdN1uxFrrxvLeQylv3pjndzrwpPf5wQCt/wExo2Jipv+3ggWAkiYZnYgDwa0VT3+ukRk8AF2oaEi1fSf6Piaiu7FFIvGW8EV/RRbbHDjVYkRbGGq5w2+Llj0qr3Zu5kHPFKFyq3m8/0WRLStw6yQy8J+JuTgmqGhM7mm55a2Kh72XNcbkiF9MkR2k4mLeqtcqGbPJ2cvRh9zOIirrL1ecOvQY+n6f2JcOj/zFecaAegmJ1+JbUVot5sYb9MbxN6yJG3xUmaImc3svjI8KMDQnyN3etLwQWBUc7EnCQvAdYhahweigZjY3bElyA3xO95RYHkRzttBi+o1994wfVrZWgFdZP+9XJGxCguqkd1GUGovVzdLG2iNdYS/v//UFkmQF9h9FTFATGynZ1V/xi/Z7SR3c/b6cyLmZGbRy7tYLKZ4TtGIfzgl1dXY5zDtzHxLLHgmiGshX65i3wuf0p1TuUbMGzNCh29KKjNTmdH5YRSOupgeKtpTAlma05QAL6dSem1mQ/++oOpM68KY0464hbGc3HT4VQRP04WBLm+fo5cAELUYXFqZsHu3zPwuOsbfC4D/y2DEB+wbi7LPuYxbGdf3GcbrCdBj/Pq0tRq6hSRNv83ssd1rq6Vbfj16cmvQ/50TuUPoFDLwit3HXziw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
