---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAkGpeFGzMWsC5nZbPrDENvuNfuO+k2jZ0/kWLsqQxZQuk/AH/RbFNYjZlTtIqNOezh3MVHDjBNgAPXAfxNlBLdmJCpYWJiGIqECH3RScuiFLbKcQw7vI9A/fhk6tfS/jkk2PDv0sp2tWqWNO9Huz0qsHH66QDP0JIRkhO0ew27IX1g1KfQF4zP/hM/uMf2s5Au0VN9Iic+C48cHAJ4zJCwp0GRWbCGQ7IzhGO0N59DsTdEFI9ZooWfXMFSIADLXHJBuxU9LC+8OKUnMCQMTRoLeGCROkaUIgdzH0cpM8dsTHoolnXJ8zTIqknug13XukyXHLFsP3tcm+gCKie/0tDBTPPN23F303LlMdL5dEbJfQGr+XYLZLilpnzdLBj3bHKXFBgcHpV6Xb3jpW7ikVYwm/eiUHPXsHOE7a7yf83WIBPE6HAwV0GUlyUB+conzgjO9njm2MFQOdcKGLpz/PNRwtIF8lXlA+3wIfgrQejnX40JrDx5BmL9K6OjuEV6osqoMTyqqLbKvMZSEgXW0CTRq0UCiRU/wr9IrZWDz9Fk5KQfZUMg0eM2sTS02Xfl3yu+uWpAQGfjk3o6Ou42L6PmFSgd0DyLJYpJhuc54rnWQcNV71WlGprbsiOPEwQ7xGvMuIS3j3B9LdoZMYJpk2/lsWha7mgzTHQMUzDNk5sA6U7P0AsNNZeg+LjsBNorsLUf54B6AczmI33WOvgRqEKDKH/MrMK2sLPqtzR66l7r9KTa9lTnHOuaWeesLluBXNZEjQPHW3eroNOWDbiAOk4IkrYkeB3mn9llFx1D0cnoe6Tgyi5/bMv8rk5AgKdgid4aDc75fZje2dWgB+kBDkdLcuGHE8XIoK0+aGaR2fZDddyPPzhP4aJg2q25I1wiM16vMYSglauDzEusxGuywupyk09B9/jjFgZUMvfxCouAEyelbzFfnGkryAgLOYqrTl0l8wu2Jz5Tsz4NeY12VR+7yhzzWp0nTQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
