---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCmEhyABFn0gAZ5ocNXYbbqwANjcs4WwCAIFBUmz1d03o9eBZOmtK7SnjCchWWDqwDe2TLDGgSRdnJsVW2EkkXDgxSfIi7x4qhBPfdu071e/PUR2iMCdU8Az2ofgXJfzHJGqZrwsz2r3tez48mZIl+hhV0fr/BVpXo7JnpdpvTMEz1gO1Sn4pSjPWWFAz+icnAUzlxOiICCpNIJ5dWAx/p9k3ueHgrLgcsoJDPed5Aiq7Gwu4sv4h8h3am6d9dlbI1jbiYFHBUlGcFq/ccH4koGGpo2pse18f7ZH20VZbMHw3CZuVMbxOcph3PV4tMAf2JtkziARatWeYN9HA86XvXLZEFnc5f8ofVj3jRFQIbVF/9w+U8ctkBa9o3QJiz78zdXhn1GRqisaYhxJ5UM6CLhF2yhxY0Fs1k5Amkzttsa01jLipJY7wyZgtooElyAIqZKJkDE8DoL3GNXSzSM2fOe8MF+6kPEwWOyr7c2lyKCQfPlqn+j0txIHcpD+dJy7OhpBiAHlbH/AJ3GEjsvXndAfF1Gntb+l21pPCoRUejXTXA/ZqcqNC0KGfq1NlpxqNLhk/qs4uhWw5amdRRSzFnT3rHDrlPNp74ZXxWttI5noMjQfv33z/MgaIJh9cdFxkyyegg+zuqh2s2nipsFHPALp74vwxsMOU+PwBxNbbVe7u9sBs+zoEVRMhQiahyRWtDgPsYcyHJS5U/5CM9ynB3Ocyuh+VXBUnUpac1fnKzZNduVnLdyLsFzivXVGcGT0xJtC0meEU6LSL91AJt3NWAyuWx9oQt71UmYs/2Bqze5nCd6CBv176T3RADj7sijU68kodjcEEn1+EqI8CwiLJd2AmJa6qP4lF6iaEq3SHUmZPvwPiFHYvXa7zO2mve6BUrhqo9f1vzt0p2unNvP3OiNNW2bHNflhtA0CzyBGZ6mOU1G5Iu3lD0YH3msiLz9PUVrjXL4d2Z5wQejjhmyRArz3VSlrpuNyw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
