---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBPwvzXjqOszBaxxqEmu3uwsmr8sq7ly/ty2ayD4AfkZZSJV7PLgzDUCmJzSJmrwR8pvYx2G7BOpNYgUfwaBQFlHGKhsweVdbiJILo/fSh5Zud714HsOr7+ObUasZkhqTNA410eoxiSMyFZCP4F1W9Z2IP3eO/H1Sy3wbKqYy+wJ/rW9Xzmf4rPLKOeRUoMKjCgRFrd4EnW45FMu3CbNEQuK69skJXK9UneZxXz/Jh7n9t+gUdYA+2jYeAHrhipNpgtC/ral0mNkV74SM/Rv/xI01KKvUdWXz4LWUIJNWq4uYIdwD5fu9n04XQk2XM6lUWLnut3ZfDfNo2tMkMPajfS58ilOMY5wDY+mi6YJWPrkD08ZmeE4eHoHr+legpZFzP+f5+mVMZLRmNxj4gOd6ehezV7d5dTz5oSpUIt87r8FbFuUdFnh4rUp4qAh+SrxCD1II1wEeJ7TYUqw8by8imPhbmGp3akx1oDwEaQBVsvY7spIyrStxv9H9NRxMSYK35j76L2ErM2VXxRYOBfbRloZAVS/tndT1a9O79pSb9vW/vQIIwa9wII7UKh7uTZw37uG8huaubxOBQPJATZq9FAFwTxRVNqsSzJ/v4RGtWgAQwRoLmTUN/bjSTs9t/ZEPLgR8CRqxq9ZhHvpcwaGZsNwueehD46InvhP1T9UepVfXk5qOrGgPRnyqjjtqhZFYHxPgFIAhLAUAfLDtzH+CtC+jN3FSdAOu7T7xpx+ok94jfBOLKfL3k+OtLwgGo0yoHf2t6ki2QYfqqg4DcqrG4hwnBX4MOI7DMp9pLxpORlaey0G4ENy5bWWuCq9/AlbncqMqR379rVjuHtur1YFYTOKIfCXYgB1MJfqGvwubtq7nNw6d9VDOr4ccSzIDxYHCB0dtxSUfuoqjjhYWde9iaf9e/X6CchYNrI2/XDBKRueJTULl/4T5qFo0VUbSKJ5tQV7T2t03LnBgF8WpUMIJUMzJ/daGA5CA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
