---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBcB/t7cP42/I3FGUO+d5mpRpxap0ol5hgQSjCY9nu4J8s6W+g3r/+7roAMoqfQzUBFgXWJgdayRMUSD9hePoyRBPWEW1QRw+6hHECHCo/DNOjNYhXo440ezixJ+4VWyKmRwoQpzzBSuV6rs6IOu9SmCdPTO8XZy+LzQrDfFwoUifRlxF+8cs2K9g7ZID5AI+yQJ04bzQF+JRmfLKg97Bgg+MZffTBl03HklmaTkyylrAgVthllfr3vYKXj4yq25e89DC+/ZEdhM3aNItWPVpuLDsQWJ4Zze0c4TjouTLm80+tTz5ZDKc1zMQD4+I5BP+1gAjfKFTn6GEfElWMh32BOSVHzM5fZfhvUXzY0XctKwzoJNmuKNyuct7qyvhu6LIwJ+56cITtnKOQXOy/k7mUJeN2xHVULlSoUW01mmOqRCLcPpDDn/yecl5SIpblDjNRAGxobl+dNzGjoeq8+s4N+qLeywKvmj1tSHevjN31h2WaFRZ7RecU8kIIWxdXnmdMdn6aJ8uDcERrKlJKidxcgnStZb2hFxSl4zIdFbbnNL45cPkppyMkMeXCrJWmDCO+McmYsw03wNDKetibTsuNgnSJubYiT5G+ojWP9BOeSeqYj45KmAvL1vtiH/w/yXEBli0/zAoiN0F++1hETZMHVckcj133yMZ+1+SE8QdKpbmJ0J+8T78I7WamUpUdryxihd1ps5oRyX62Jy29uO/LO7Akb9evzOIUIf63Ix0c8lqZjDqUbBrugPy114EOGPrKQ9HyD6u8z9lINho/0N8C/cKligDr2os2uLXNlNQMSRJdcYUeX/kNW3hB9YXQQQwefFdiEQrQCooAaFSO3c1qzuVDQs23lMFFe/QrRnfivnViC55QubRkZVF8+m/3cMk6JJyOq6mFaeE+NDZEx5L61JyG0HQGurF/pKNWHJSHw5U/D+terrMKgyfw178eANGYZfVPGM7VODFD4La5ZR30DXJwA46IMxQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
