# Api gateway microservice (CURRENTLY STABLE BASE IS LATEST 0.1.5

# FROM ghcr.io/biosimulators/bio-check-base:latest TODO: change this back to latest below
FROM ghcr.io/biosimulators/bio-check-base:0.2.2-test

SHELL ["/usr/bin/env", "bash", "-c"]

# RUN mkdir api

# COPY . /app/api

COPY ./ ./

EXPOSE 3001

RUN source ~/.bashrc \
    && poetry install --only=api --no-cache

# WORKDIR /app/api

ENTRYPOINT ["bash", "-c", "source ~/.bashrc && poetry run uvicorn main:app --host 0.0.0.0 --port 3001 --reload"]

