# Api container

# TODO: Ensure read from BASE_VERSION.txt
FROM ghcr.io/biosimulators/bio-check-base:latest

WORKDIR /app

COPY . /app/api

EXPOSE 3001

WORKDIR /app/api

# RUN pip install --upgrade google-cloud-storage

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]

