# Api container (CURRENTLY STABLE BASE IS LATEST 0.1.5

FROM ghcr.io/biosimulators/bio-check-base:latest

RUN mkdir api

COPY . /app/api

EXPOSE 3001

# RUN /app/assets/install_deps.sh /app/api/requirements.api.txt

ENV PATH="/root/.local/bin:$PATH"

RUN poetry install --only=api

WORKDIR /app/api

RUN python3 -c "import os;files=os.listdir();import shutil;[shutil.rmtree(f) if '__pycache__' in f else None for f in files]"

ENTRYPOINT ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]

